### ISSUE TITLE
Sanity Check: Minted Variable

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/filecoin-consensus-pledge-demo#11]
Sanity checking that this variable should not be added but should be set over

<img width="668" alt="image" src="https://user-images.githubusercontent.com/28468980/225126617-4c21b71c-0cd4-4fcd-9589-87d6139dc389.png">

**Comment by danlessa** [comment]
@SeanMcOwen yes it should be set over because the Total Amount of FIL Minted at Any Time is governed by the Simple + Baseline Minting Functions. In fact, the Daily Reward (per spec) is defined as being the difference between the issuance at Today minus the issuance at Yesterday.
