### ISSUE TITLE
Should this be based on target or actual?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/filecoin-consensus-pledge-demo#13]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/28468980/225966985-dc2582f6-9225-4c93-9cd4-669a5a6fdf3b.png">

**Comment by jackhack00** [comment]
@SeanMcOwen if you're talking about locked_supply then target is correct (TLS, tunable param, 30% for regular scenario and 0 for comparative scenario)

**Comment by SeanMcOwen** [comment]
I was about to close this, I realize now the purpose. Just raising these so I do not forget, but it makes sense now
